services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: 12345

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgresql://postgres:12345@db:5432/postgres'
      LOG_TO_FILE: 'true'
      DEBUG_LEVEL_LOG: 'true'
    ports:
      - '3000:3000'