/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacoteRouteImport } from './routes/pacote'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FigurinhasIndexRouteImport } from './routes/figurinhas/index'
import { Route as FigurinhasNovaRouteImport } from './routes/figurinhas/nova'
import { Route as FigurinhasIdRouteImport } from './routes/figurinhas/$id'
import { Route as FigurinhasIdEditarRouteImport } from './routes/figurinhas/$id_.editar'

const PacoteRoute = PacoteRouteImport.update({
  id: '/pacote',
  path: '/pacote',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FigurinhasIndexRoute = FigurinhasIndexRouteImport.update({
  id: '/figurinhas/',
  path: '/figurinhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FigurinhasNovaRoute = FigurinhasNovaRouteImport.update({
  id: '/figurinhas/nova',
  path: '/figurinhas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const FigurinhasIdRoute = FigurinhasIdRouteImport.update({
  id: '/figurinhas/$id',
  path: '/figurinhas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FigurinhasIdEditarRoute = FigurinhasIdEditarRouteImport.update({
  id: '/figurinhas/$id_/editar',
  path: '/figurinhas/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/pacote': typeof PacoteRoute
  '/figurinhas/$id': typeof FigurinhasIdRoute
  '/figurinhas/nova': typeof FigurinhasNovaRoute
  '/figurinhas/': typeof FigurinhasIndexRoute
  '/figurinhas/$id/editar': typeof FigurinhasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/pacote': typeof PacoteRoute
  '/figurinhas/$id': typeof FigurinhasIdRoute
  '/figurinhas/nova': typeof FigurinhasNovaRoute
  '/figurinhas': typeof FigurinhasIndexRoute
  '/figurinhas/$id/editar': typeof FigurinhasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/pacote': typeof PacoteRoute
  '/figurinhas/$id': typeof FigurinhasIdRoute
  '/figurinhas/nova': typeof FigurinhasNovaRoute
  '/figurinhas/': typeof FigurinhasIndexRoute
  '/figurinhas/$id_/editar': typeof FigurinhasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/pacote'
    | '/figurinhas/$id'
    | '/figurinhas/nova'
    | '/figurinhas/'
    | '/figurinhas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/pacote'
    | '/figurinhas/$id'
    | '/figurinhas/nova'
    | '/figurinhas'
    | '/figurinhas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/pacote'
    | '/figurinhas/$id'
    | '/figurinhas/nova'
    | '/figurinhas/'
    | '/figurinhas/$id_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  PacoteRoute: typeof PacoteRoute
  FigurinhasIdRoute: typeof FigurinhasIdRoute
  FigurinhasNovaRoute: typeof FigurinhasNovaRoute
  FigurinhasIndexRoute: typeof FigurinhasIndexRoute
  FigurinhasIdEditarRoute: typeof FigurinhasIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pacote': {
      id: '/pacote'
      path: '/pacote'
      fullPath: '/pacote'
      preLoaderRoute: typeof PacoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figurinhas/': {
      id: '/figurinhas/'
      path: '/figurinhas'
      fullPath: '/figurinhas/'
      preLoaderRoute: typeof FigurinhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figurinhas/nova': {
      id: '/figurinhas/nova'
      path: '/figurinhas/nova'
      fullPath: '/figurinhas/nova'
      preLoaderRoute: typeof FigurinhasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figurinhas/$id': {
      id: '/figurinhas/$id'
      path: '/figurinhas/$id'
      fullPath: '/figurinhas/$id'
      preLoaderRoute: typeof FigurinhasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figurinhas/$id_/editar': {
      id: '/figurinhas/$id_/editar'
      path: '/figurinhas/$id/editar'
      fullPath: '/figurinhas/$id/editar'
      preLoaderRoute: typeof FigurinhasIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  PacoteRoute: PacoteRoute,
  FigurinhasIdRoute: FigurinhasIdRoute,
  FigurinhasNovaRoute: FigurinhasNovaRoute,
  FigurinhasIndexRoute: FigurinhasIndexRoute,
  FigurinhasIdEditarRoute: FigurinhasIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
